/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TradingSetup = IDL.Record({
  'pairSymbol' : IDL.Text,
  'name' : IDL.Text,
  'takeProfitPrice' : IDL.Float64,
  'accountBalance' : IDL.Float64,
  'stopLossPrice' : IDL.Float64,
  'riskPercentage' : IDL.Float64,
  'notes' : IDL.Opt(IDL.Text),
  'entryPrice' : IDL.Float64,
  'accountCurrency' : IDL.Text,
  'lotSize' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteSetup' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSetup' : IDL.Func([IDL.Nat], [TradingSetup], ['query']),
  'getSetups' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, TradingSetup))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSetup' : IDL.Func([TradingSetup], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TradingSetup = IDL.Record({
    'pairSymbol' : IDL.Text,
    'name' : IDL.Text,
    'takeProfitPrice' : IDL.Float64,
    'accountBalance' : IDL.Float64,
    'stopLossPrice' : IDL.Float64,
    'riskPercentage' : IDL.Float64,
    'notes' : IDL.Opt(IDL.Text),
    'entryPrice' : IDL.Float64,
    'accountCurrency' : IDL.Text,
    'lotSize' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteSetup' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSetup' : IDL.Func([IDL.Nat], [TradingSetup], ['query']),
    'getSetups' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, TradingSetup))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSetup' : IDL.Func([TradingSetup], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };